### ISSUE TITLE
Assignment 1 is ready for grading 

### ISSUE THREAD

**Issue by jhorowitz1996** [SES-5215-F2020/jhorowitz-quant#1]
Both the .rmd  and html file are ready for your grading. I look forward to hearing your thoughts. I hope it's a homerun (baseball pun because used a baseball dataset). :)

**Comment by saratepfer** [comment]
Thank you, Jennifer! I'm so sorry you didn't get feedback sooner. Somehow your issue got skipped. Please see comments on code and content below.

**Comments on Content**
- Please include a statement that explicitly describes: your sample population, the number of observations in your sample, and the unit of analysis.
- It seems your knitted HTML (https://ses-5215-f2020.github.io/jhorowitz-quant/Assignment1.html) is different from your RMD. Is there another html file that we should be reviewing? (one that includes baseball stats?) Please feel free to push that one to Github too, and we can review it.
 
**Comments on Code**
- Line 12: replace {r load libraries} with {r load libraries, message = FALSE} to prevent additional, unnecessary messages from cluttering your RMD.
